### ISSUE TITLE
Uncaught Error: '$ATOM_HOME/storage/reduced-dark-ui/font.less' wasn't found

### ISSUE THREAD

**Issue by mfplinta** [tuomashatakka/reduced-dark-ui#25]
Clean installation of most recent atom.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Ubuntu Zesty
**Thrown From**: [reduced-dark-ui](https://github.com/tuomashatakka/reduced-dark-ui) package 0.9.2

### Stack Trace

Uncaught Error: '/home/matheus/.atom/storage/reduced-dark-ui/font.less' wasn't found

```
At /usr/share/atom/resources/app.asar/src/theme-manager.js:301

Error
    at /app.asar/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/app.asar/node_modules/less-cache/lib/less-cache.js:255:16)
    at LessCache.module.exports.LessCache.cssForFile (/app.asar/node_modules/less-cache/lib/less-cache.js:286:20)
    at LessCache.module.exports.LessCache.readFileSync (/app.asar/node_modules/less-cache/lib/less-cache.js:274:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/app.asar/src/theme-manager.js:282:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/app.asar/src/theme-manager.js:258:21)
    at ConfigManagerAnew.didFinishTransaction (/packages/reduced-dark-ui/lib/core/configuration/Config.js:50:32)
    at /packages/reduced-dark-ui/lib/core/configuration/Config.js:85:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:15.8.0 core:confirm (input.hidden-input)
     -2:11.2.0 core:backspace (input.hidden-input)
     -2:04.5.0 core:paste (input.hidden-input)
  2x -2:04.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
reduced-dark-ui 0.9.2 
```

**Comment by tuomashatakka** [comment]
I'll take a closer look into this. Does .atom/storage/reduced-dark-ui folder exist?  Does the theme throw error if activated again? 😃

**Comment by mfplinta** [comment]
Hello :smiley: ! Thanks for answering!

The folder .atom/storage/reduced-dark-ui apparently exists.
![screen cap 3](https://cloud.githubusercontent.com/assets/7898162/23343092/ae34422a-fc44-11e6-8e39-fe8a09e6bdda.png)

Re-activating the theme don't seems to resolve :disappointed: 
![screen cap 2](https://cloud.githubusercontent.com/assets/7898162/23343093/ae3ad4fa-fc44-11e6-800f-ad3808c825cf.png)

And when I restart the Atom with the theme activated, the white dead screen shows.
![screen cap 1](https://cloud.githubusercontent.com/assets/7898162/23343094/ae3b9700-fc44-11e6-8865-e1292cdacbdc.png)

I'm running Ubuntu 17.04 :dog: 
![screen cap 4](https://cloud.githubusercontent.com/assets/7898162/23343133/435b172a-fc45-11e6-9c0d-36d06b38c202.png)

Thanks again and good luck ;)

**Comment by tuomashatakka** [comment]
Thanks for the comprehensive images 😊 

That's really odd. It may have something to do with access control. Or something else. 🙃

I'm currently working on moving from less variables to pure css variables which means all of that less file io may be abandoned. The sequence for checking the storage's files is rather complicated so I think it's best just to finish the new implementation. I'll try to get it done as fast as possible to allow you to enable the theme 🙋 Ps. the update makes the config updates a lot faster than any other theme out there since afaik none of them uses the css variables just yet 😃

**Comment by tuomashatakka** [comment]
@mfplinta I got to accidentally recreate this error on my local environment!

The latest commit (38ac378c0aeeaffc0b1dd04df030eb1eb32600cf) has the fix to this, so if you want to, you may apply it to your local copy of the package - I won't publish it just yet, since there are some css variable definitions still unconfigured :)

**Comment by tuomashatakka** [comment]
I may cherry-pick that commit to the apm later this evening. I still don't know why less parser occasionally thinks that the font.less does not exist - my bet is that it fails to read the file if it's being written to at the same time.
